using System;
using System.Collections.Generic;

namespace CoptLib.Writing;

partial class DisplayFont
{
    public const string CopticStandardMapId = "CopticStandard";
    public const string UnicodeMapId = nameof(Unicode);
    public const string UnicodeBMapId = nameof(UnicodeB);

    public static readonly List<DisplayFont> Fonts = new()
    {
        CopticStandard, Unicode, UnicodeB,
        Athanasius, CopticInGreekUnicode
    };

    public static DisplayFont CopticStandard => new()
    {
        DisplayName = "Coptic Standard",
        FontFamily = "CS Avva Shenouda",
        CharacterMapId = CopticStandardMapId,
        IsJenkimBefore = true,
        Charmap = CreateMapping(ConvertToCopticStandard)
    };

    public static DisplayFont Unicode => new()
    {
        DisplayName = "Unicode",
        FontFamily = "Noto Sans",
        CharacterMapId = UnicodeMapId,
        IsJenkimBefore = false,
        Charmap = CreateMapping(ConvertToUnicode)
    };

    public static DisplayFont UnicodeB => new()
    {
        DisplayName = "Unicode B",
        FontFamily = "Segoe UI",
        IsJenkimBefore = true,
        CharacterMapId = UnicodeBMapId,
        Charmap = CreateMapping(ConvertToUnicode)
    };

    public static DisplayFont Athanasius => new()
    {
        DisplayName = "Athanasius",
        FontFamily = "Athanasius Plain",
        CharacterMapId = nameof(Athanasius),
        IsJenkimBefore = true,
        Charmap = CreateMapping(ConvertToAthanasius)
    };

    public static DisplayFont CopticInGreekUnicode => new()
    {
        DisplayName = "Greek Unicode",
        FontFamily = "Noto Sans",
        CharacterMapId = nameof(CopticInGreekUnicode),
        IsJenkimBefore = false,
        Charmap = CreateMapping(ConvertToCopticInGreekUnicode)
    };

    public static DisplayFont CopticInGreekUnicodeB => new()
    {
        DisplayName = "Greek Unicode B",
        FontFamily = "Segoe UI",
        CharacterMapId = nameof(CopticInGreekUnicodeB),
        IsJenkimBefore = true,
        Charmap = CreateMapping(ConvertToCopticInGreekUnicode)
    };

    public static DisplayFont GreekInCopticUnicode => new()
    {
        DisplayName = "Greek Unicode B",
        FontFamily = "Noto Sans",
        CharacterMapId = nameof(GreekInCopticUnicode),
        IsJenkimBefore = false,
        Charmap = CreateMapping(ConvertToGreekInCopticUnicode)
    };

    private static DoubleDictionary<KnownCharacter, char> CreateMapping(Func<KnownCharacter, char> mapper)
    {
        var knownChars = (KnownCharacter[]) Enum.GetValues(typeof(KnownCharacter));
        DoubleDictionary<KnownCharacter, char> map = new(knownChars.Length)
        {
            (KnownCharacter.Default, '\0')
        };
        
        foreach (var c in knownChars)
        {
            map.Add(c, mapper(c));
        }
        
        return map;
    }

    private static char ConvertToCopticStandard(KnownCharacter c)
    {
        var ci = (int) c;
        if (ci is >= (int) KnownCharacter.LatinCapitalA and <= (int) KnownCharacter.GreekSmallOmega)
            return '\0';

        return c switch
        {
            KnownCharacter.Ampersand or
                KnownCharacter.Apostrophe or
                KnownCharacter.Tilde or
                KnownCharacter.InvertedExclamationMark or
                KnownCharacter.CurrencySign or
                KnownCharacter.InvertedQuestionMark or
                KnownCharacter.CopticPiRo or
                KnownCharacter.QuotationMark => '\0',
            KnownCharacter.Comma => '>',
            KnownCharacter.Colon => '@',
            KnownCharacter.Semicolon => '&',
            KnownCharacter.LessThanSign => '«',
            KnownCharacter.EqualsSign => '_',
            KnownCharacter.GreaterThanSign => '»',
            KnownCharacter.CommercialAt => 'Î',
            KnownCharacter.LeftCurlyBracket => '„',
            KnownCharacter.VerticalLine => 'ƒ',
            KnownCharacter.RightCurlyBracket => '…',
            KnownCharacter.CentSign => '—',
            KnownCharacter.YenSign => '™',
            KnownCharacter.CombiningGraveAccent => '`',
            KnownCharacter.CombiningAcuteAccent => 'È',
            KnownCharacter.CombiningOverline => '=',
            KnownCharacter.CopticCapitalAlpha => 'A',
            KnownCharacter.CopticCapitalVida => 'B',
            KnownCharacter.CopticCapitalGamma => 'G',
            KnownCharacter.CopticCapitalDalda => 'D',
            KnownCharacter.CopticCapitalEie => 'E',
            KnownCharacter.CopticCapitalSou or
                KnownCharacter.CopticSmallSou => '^',
            KnownCharacter.CopticCapitalZata => 'Z',
            KnownCharacter.CopticCapitalHate => 'Y',
            KnownCharacter.CopticCapitalThethe => ':',
            KnownCharacter.CopticCapitalIauda => 'I',
            KnownCharacter.CopticCapitalKapa => 'K',
            KnownCharacter.CopticCapitalLaula => 'L',
            KnownCharacter.CopticCapitalMi => 'M',
            KnownCharacter.CopticCapitalNi => 'N',
            KnownCharacter.CopticCapitalKsi => 'X',
            KnownCharacter.CopticCapitalO => 'O',
            KnownCharacter.CopticCapitalPi => 'P',
            KnownCharacter.CopticCapitalRo => 'R',
            KnownCharacter.CopticCapitalSima => 'C',
            KnownCharacter.CopticCapitalTau => 'T',
            KnownCharacter.CopticCapitalUa => 'U',
            KnownCharacter.CopticCapitalFi => 'V',
            KnownCharacter.CopticCapitalKhi => '<',
            KnownCharacter.CopticCapitalPsi => '"',
            KnownCharacter.CopticCapitalOou => 'W',
            KnownCharacter.CopticCapitalShei => 'S',
            KnownCharacter.CopticCapitalFei => 'F',
            KnownCharacter.CopticCapitalKhei => 'Q',
            KnownCharacter.CopticCapitalHori => 'H',
            KnownCharacter.CopticCapitalGangia => 'J',
            KnownCharacter.CopticCapitalShima => '{',
            KnownCharacter.CopticCapitalDei => '}',
            KnownCharacter.CopticCapitalAkhmimicKhei or
                KnownCharacter.CopticSmallAkhmimicKhei => '|',
            KnownCharacter.CopticSmallAlpha => 'a',
            KnownCharacter.CopticSmallVida => 'b',
            KnownCharacter.CopticSmallGamma => 'g',
            KnownCharacter.CopticSmallDalda => 'd',
            KnownCharacter.CopticSmallEie => 'e',
            KnownCharacter.CopticSmallZata => 'z',
            KnownCharacter.CopticSmallHate => 'y',
            KnownCharacter.CopticSmallThethe => ';',
            KnownCharacter.CopticSmallIauda => 'i',
            KnownCharacter.CopticSmallKapa => 'k',
            KnownCharacter.CopticSmallLaula => 'l',
            KnownCharacter.CopticSmallMi => 'm',
            KnownCharacter.CopticSmallNi => 'n',
            KnownCharacter.CopticSmallKsi => 'x',
            KnownCharacter.CopticSmallO => 'o',
            KnownCharacter.CopticSmallPi => 'p',
            KnownCharacter.CopticSmallRo => 'r',
            KnownCharacter.CopticSmallSima => 'c',
            KnownCharacter.CopticSmallTau => 't',
            KnownCharacter.CopticSmallUa => 'u',
            KnownCharacter.CopticSmallFi => 'v',
            KnownCharacter.CopticSmallKhi => ',',
            KnownCharacter.CopticSmallPsi => '\'',
            KnownCharacter.CopticSmallOou => 'w',
            KnownCharacter.CopticSmallShei => 's',
            KnownCharacter.CopticSmallFei => 'f',
            KnownCharacter.CopticSmallKhei => 'q',
            KnownCharacter.CopticSmallHori => 'h',
            KnownCharacter.CopticSmallGangia => 'j',
            KnownCharacter.CopticSmallShima => '[',
            KnownCharacter.CopticSmallDei => ']',
            KnownCharacter.CopticMiRo => '¢',
            KnownCharacter.CopticStauros => '½',
            KnownCharacter.CopticTauRo => '¤',
            KnownCharacter.CopticKhiRo => '¥',
            KnownCharacter.CopticShimaSima => '¡',
            KnownCharacter.CopticParthenos => '¦',
            KnownCharacter.CopticMiEie => '£',
            KnownCharacter.CopticSynTheo => '¨',
            _ => '\0'
        };
    }

    private static char ConvertToUnicode(KnownCharacter c)
    {
        return c switch
        {
            KnownCharacter.ExclamationMark => '!',
            KnownCharacter.QuotationMark => '"',
            KnownCharacter.NumberSign => '#',
            KnownCharacter.DollarSign => '$',
            KnownCharacter.PercentSign => '%',
            KnownCharacter.Ampersand => '&',
            KnownCharacter.Apostrophe => '\'',
            KnownCharacter.LeftParenthesis => '(',
            KnownCharacter.RightParenthesis => ')',
            KnownCharacter.Asterisk => '*',
            KnownCharacter.PlusSign => '+',
            KnownCharacter.Comma => ',',
            KnownCharacter.HyphenMinus => '-',
            KnownCharacter.FullStop => '.',
            KnownCharacter.Solidus => '/',
            KnownCharacter.Colon => ':',
            KnownCharacter.Semicolon => ';',
            KnownCharacter.LessThanSign => '<',
            KnownCharacter.EqualsSign => '=',
            KnownCharacter.GreaterThanSign => '>',
            KnownCharacter.QuestionMark => '?',
            KnownCharacter.CommercialAt => '@',
            KnownCharacter.LeftCurlyBracket => '{',
            KnownCharacter.VerticalLine => '|',
            KnownCharacter.RightCurlyBracket => '}',
            KnownCharacter.Tilde => '~',
            KnownCharacter.InvertedExclamationMark => '¡',
            KnownCharacter.CentSign => '¢',
            KnownCharacter.CurrencySign => '¤',
            KnownCharacter.YenSign => '¥',
            KnownCharacter.SectionSign => '§',
            KnownCharacter.InvertedQuestionMark => '¿',
            KnownCharacter.CombiningGraveAccent => '\u0300',
            KnownCharacter.CombiningAcuteAccent => '\u0301',
            KnownCharacter.CombiningOverline => '\u0305',
            KnownCharacter.LatinCapitalA => 'A',
            KnownCharacter.LatinCapitalB => 'B',
            KnownCharacter.LatinCapitalC => 'C',
            KnownCharacter.LatinCapitalD => 'D',
            KnownCharacter.LatinCapitalE => 'E',
            KnownCharacter.LatinCapitalF => 'F',
            KnownCharacter.LatinCapitalG => 'G',
            KnownCharacter.LatinCapitalH => 'H',
            KnownCharacter.LatinCapitalI => 'I',
            KnownCharacter.LatinCapitalJ => 'J',
            KnownCharacter.LatinCapitalK => 'K',
            KnownCharacter.LatinCapitalL => 'L',
            KnownCharacter.LatinCapitalM => 'M',
            KnownCharacter.LatinCapitalN => 'N',
            KnownCharacter.LatinCapitalO => 'O',
            KnownCharacter.LatinCapitalP => 'P',
            KnownCharacter.LatinCapitalQ => 'Q',
            KnownCharacter.LatinCapitalR => 'R',
            KnownCharacter.LatinCapitalS => 'S',
            KnownCharacter.LatinCapitalT => 'T',
            KnownCharacter.LatinCapitalU => 'U',
            KnownCharacter.LatinCapitalV => 'V',
            KnownCharacter.LatinCapitalW => 'W',
            KnownCharacter.LatinCapitalX => 'X',
            KnownCharacter.LatinCapitalY => 'Y',
            KnownCharacter.LatinCapitalZ => 'Z',
            KnownCharacter.LatinSmallA => 'a',
            KnownCharacter.LatinSmallB => 'b',
            KnownCharacter.LatinSmallC => 'c',
            KnownCharacter.LatinSmallD => 'd',
            KnownCharacter.LatinSmallE => 'e',
            KnownCharacter.LatinSmallF => 'f',
            KnownCharacter.LatinSmallG => 'g',
            KnownCharacter.LatinSmallH => 'h',
            KnownCharacter.LatinSmallI => 'i',
            KnownCharacter.LatinSmallJ => 'j',
            KnownCharacter.LatinSmallK => 'k',
            KnownCharacter.LatinSmallL => 'l',
            KnownCharacter.LatinSmallM => 'm',
            KnownCharacter.LatinSmallN => 'n',
            KnownCharacter.LatinSmallO => 'o',
            KnownCharacter.LatinSmallP => 'p',
            KnownCharacter.LatinSmallQ => 'q',
            KnownCharacter.LatinSmallR => 'r',
            KnownCharacter.LatinSmallS => 's',
            KnownCharacter.LatinSmallT => 't',
            KnownCharacter.LatinSmallU => 'u',
            KnownCharacter.LatinSmallV => 'v',
            KnownCharacter.LatinSmallW => 'w',
            KnownCharacter.LatinSmallX => 'x',
            KnownCharacter.LatinSmallY => 'y',
            KnownCharacter.LatinSmallZ => 'z',
            KnownCharacter.GreekCapitalAlpha => 'Α',
            KnownCharacter.GreekCapitalBeta => 'Β',
            KnownCharacter.GreekCapitalGamma => 'Γ',
            KnownCharacter.GreekCapitalDelta => 'Δ',
            KnownCharacter.GreekCapitalEpsilon => 'Ε',
            KnownCharacter.GreekCapitalZeta => 'Ζ',
            KnownCharacter.GreekCapitalEta => 'Η',
            KnownCharacter.GreekCapitalTheta => 'Θ',
            KnownCharacter.GreekCapitalIota => 'Ι',
            KnownCharacter.GreekCapitalKappa => 'Κ',
            KnownCharacter.GreekCapitalLambda => 'Λ',
            KnownCharacter.GreekCapitalMu => 'Μ',
            KnownCharacter.GreekCapitalNu => 'Ν',
            KnownCharacter.GreekCapitalXi => 'Ξ',
            KnownCharacter.GreekCapitalOmicron => 'Ο',
            KnownCharacter.GreekCapitalPi => 'Π',
            KnownCharacter.GreekCapitalRho => 'Ρ',
            KnownCharacter.GreekCapitalSigma => 'Σ',
            KnownCharacter.GreekCapitalTau => 'Τ',
            KnownCharacter.GreekCapitalUpsilon => 'Υ',
            KnownCharacter.GreekCapitalPhi => 'Φ',
            KnownCharacter.GreekCapitalChi => 'Χ',
            KnownCharacter.GreekCapitalPsi => 'Ψ',
            KnownCharacter.GreekCapitalOmega => 'Ω',
            KnownCharacter.GreekSmallAlpha => 'α',
            KnownCharacter.GreekSmallBeta => 'β',
            KnownCharacter.GreekSmallGamma => 'γ',
            KnownCharacter.GreekSmallDelta => 'δ',
            KnownCharacter.GreekSmallEpsilon => 'ε',
            KnownCharacter.GreekSmallZeta => 'ζ',
            KnownCharacter.GreekSmallEta => 'η',
            KnownCharacter.GreekSmallTheta => 'θ',
            KnownCharacter.GreekSmallIota => 'ι',
            KnownCharacter.GreekSmallKappa => 'κ',
            KnownCharacter.GreekSmallLambda => 'λ',
            KnownCharacter.GreekSmallMu => 'μ',
            KnownCharacter.GreekSmallNu => 'ν',
            KnownCharacter.GreekSmallXi => 'ξ',
            KnownCharacter.GreekSmallOmicron => 'ο',
            KnownCharacter.GreekSmallPi => 'π',
            KnownCharacter.GreekSmallRho => 'ρ',
            KnownCharacter.GreekSmallFinalSigma => 'ς',
            KnownCharacter.GreekSmallSigma => 'σ',
            KnownCharacter.GreekSmallTau => 'τ',
            KnownCharacter.GreekSmallUpsilon => 'υ',
            KnownCharacter.GreekSmallPhi => 'φ',
            KnownCharacter.GreekSmallChi => 'χ',
            KnownCharacter.GreekSmallPsi => 'ψ',
            KnownCharacter.GreekSmallOmega => 'ω',
            KnownCharacter.CopticCapitalAlpha => 'Ⲁ',
            KnownCharacter.CopticCapitalVida => 'Ⲃ',
            KnownCharacter.CopticCapitalGamma => 'Ⲅ',
            KnownCharacter.CopticCapitalDalda => 'Ⲇ',
            KnownCharacter.CopticCapitalEie => 'Ⲉ',
            KnownCharacter.CopticCapitalSou => 'Ⲋ',
            KnownCharacter.CopticCapitalZata => 'Ⲍ',
            KnownCharacter.CopticCapitalHate => 'Ⲏ',
            KnownCharacter.CopticCapitalThethe => 'Ⲑ',
            KnownCharacter.CopticCapitalIauda => 'Ⲓ',
            KnownCharacter.CopticCapitalKapa => 'Ⲕ',
            KnownCharacter.CopticCapitalLaula => 'Ⲗ',
            KnownCharacter.CopticCapitalMi => 'Ⲙ',
            KnownCharacter.CopticCapitalNi => 'Ⲛ',
            KnownCharacter.CopticCapitalKsi => 'Ⲝ',
            KnownCharacter.CopticCapitalO => 'Ⲟ',
            KnownCharacter.CopticCapitalPi => 'Ⲡ',
            KnownCharacter.CopticCapitalRo => 'Ⲣ',
            KnownCharacter.CopticCapitalSima => 'Ⲥ',
            KnownCharacter.CopticCapitalTau => 'Ⲧ',
            KnownCharacter.CopticCapitalUa => 'Ⲩ',
            KnownCharacter.CopticCapitalFi => 'Ⲫ',
            KnownCharacter.CopticCapitalKhi => 'Ⲭ',
            KnownCharacter.CopticCapitalPsi => 'Ⲯ',
            KnownCharacter.CopticCapitalOou => 'Ⲱ',
            KnownCharacter.CopticCapitalShei => 'Ϣ',
            KnownCharacter.CopticCapitalFei => 'Ϥ',
            KnownCharacter.CopticCapitalKhei => 'Ϧ',
            KnownCharacter.CopticCapitalHori => 'Ϩ',
            KnownCharacter.CopticCapitalGangia => 'Ϫ',
            KnownCharacter.CopticCapitalShima => 'Ϭ',
            KnownCharacter.CopticCapitalDei => 'Ϯ',
            KnownCharacter.CopticCapitalAkhmimicKhei => 'Ⳉ',
            KnownCharacter.CopticSmallAlpha => 'ⲁ',
            KnownCharacter.CopticSmallVida => 'ⲃ',
            KnownCharacter.CopticSmallGamma => 'ⲅ',
            KnownCharacter.CopticSmallDalda => 'ⲇ',
            KnownCharacter.CopticSmallEie => 'ⲉ',
            KnownCharacter.CopticSmallSou => 'ⲋ',
            KnownCharacter.CopticSmallZata => 'ⲍ',
            KnownCharacter.CopticSmallHate => 'ⲏ',
            KnownCharacter.CopticSmallThethe => 'ⲑ',
            KnownCharacter.CopticSmallIauda => 'ⲓ',
            KnownCharacter.CopticSmallKapa => 'ⲕ',
            KnownCharacter.CopticSmallLaula => 'ⲗ',
            KnownCharacter.CopticSmallMi => 'ⲙ',
            KnownCharacter.CopticSmallNi => 'ⲛ',
            KnownCharacter.CopticSmallKsi => 'ⲝ',
            KnownCharacter.CopticSmallO => 'ⲟ',
            KnownCharacter.CopticSmallPi => 'ⲡ',
            KnownCharacter.CopticSmallRo => 'ⲣ',
            KnownCharacter.CopticSmallSima => 'ⲥ',
            KnownCharacter.CopticSmallTau => 'ⲧ',
            KnownCharacter.CopticSmallUa => 'ⲩ',
            KnownCharacter.CopticSmallFi => 'ⲫ',
            KnownCharacter.CopticSmallKhi => 'ⲭ',
            KnownCharacter.CopticSmallPsi => 'ⲯ',
            KnownCharacter.CopticSmallOou => 'ⲱ',
            KnownCharacter.CopticSmallShei => 'ϣ',
            KnownCharacter.CopticSmallFei => 'ϥ',
            KnownCharacter.CopticSmallKhei => 'ϧ',
            KnownCharacter.CopticSmallHori => 'ϩ',
            KnownCharacter.CopticSmallGangia => 'ϫ',
            KnownCharacter.CopticSmallShima => 'ϭ',
            KnownCharacter.CopticSmallDei => 'ϯ',
            KnownCharacter.CopticSmallAkhmimicKhei => 'ⳉ',
            KnownCharacter.CopticMiRo => '⳥',
            KnownCharacter.CopticPiRo => '⳦',
            KnownCharacter.CopticStauros => '⳧',
            KnownCharacter.CopticTauRo => '⳨',
            KnownCharacter.CopticKhiRo => '⳩',
            KnownCharacter.CopticShimaSima => '⳪',
            _ => '\0',
        };
    }

    private static char ConvertToCopticInGreekUnicode(KnownCharacter c)
    {
        return c switch
        {
            KnownCharacter.CopticCapitalAlpha => 'Α',
            KnownCharacter.CopticCapitalVida => 'Β',
            KnownCharacter.CopticCapitalGamma => 'Γ',
            KnownCharacter.CopticCapitalDalda => 'Δ',
            KnownCharacter.CopticCapitalEie => 'Ε',
            KnownCharacter.CopticCapitalZata => 'Ζ',
            KnownCharacter.CopticCapitalHate => 'Η',
            KnownCharacter.CopticCapitalThethe => 'Θ',
            KnownCharacter.CopticCapitalIauda => 'Ι',
            KnownCharacter.CopticCapitalKapa => 'Κ',
            KnownCharacter.CopticCapitalLaula => 'Λ',
            KnownCharacter.CopticCapitalMi => 'Μ',
            KnownCharacter.CopticCapitalNi => 'Ν',
            KnownCharacter.CopticCapitalKsi => 'Ξ',
            KnownCharacter.CopticCapitalO => 'Ο',
            KnownCharacter.CopticCapitalPi => 'Π',
            KnownCharacter.CopticCapitalRo => 'Ρ',
            KnownCharacter.CopticCapitalSima => 'Σ',
            KnownCharacter.CopticCapitalTau => 'Τ',
            KnownCharacter.CopticCapitalUa => 'Υ',
            KnownCharacter.CopticCapitalFi => 'Φ',
            KnownCharacter.CopticCapitalKhi => 'Χ',
            KnownCharacter.CopticCapitalPsi => 'Ψ',
            KnownCharacter.CopticCapitalOou => 'Υ',
            KnownCharacter.CopticSmallAlpha => 'α',
            KnownCharacter.CopticSmallVida => 'β',
            KnownCharacter.CopticSmallGamma => 'γ',
            KnownCharacter.CopticSmallDalda => 'δ',
            KnownCharacter.CopticSmallEie => 'ε',
            KnownCharacter.CopticSmallZata => 'ζ',
            KnownCharacter.CopticSmallHate => 'η',
            KnownCharacter.CopticSmallThethe => 'θ',
            KnownCharacter.CopticSmallIauda => 'ι',
            KnownCharacter.CopticSmallKapa => 'κ',
            KnownCharacter.CopticSmallLaula => 'λ',
            KnownCharacter.CopticSmallMi => 'μ',
            KnownCharacter.CopticSmallNi => 'ν',
            KnownCharacter.CopticSmallKsi => 'ξ',
            KnownCharacter.CopticSmallO => 'ο',
            KnownCharacter.CopticSmallPi => 'π',
            KnownCharacter.CopticSmallRo => 'ρ',
            KnownCharacter.CopticSmallSima => 'σ',
            KnownCharacter.CopticSmallTau => 'τ',
            KnownCharacter.CopticSmallUa => 'υ',
            KnownCharacter.CopticSmallFi => 'φ',
            KnownCharacter.CopticSmallKhi => 'χ',
            KnownCharacter.CopticSmallPsi => 'ψ',
            KnownCharacter.CopticSmallOou => 'ω',
            _ => ConvertToUnicode(c)
        };
    }

    private static char ConvertToGreekInCopticUnicode(KnownCharacter c)
    {
        return c switch
        {
            KnownCharacter.GreekCapitalAlpha => 'Ⲁ',
            KnownCharacter.GreekCapitalBeta => 'Ⲃ',
            KnownCharacter.GreekCapitalGamma => 'Ⲅ',
            KnownCharacter.GreekCapitalDelta => 'Ⲇ',
            KnownCharacter.GreekCapitalEpsilon => 'Ⲉ',
            KnownCharacter.GreekCapitalZeta => 'Ⲍ',
            KnownCharacter.GreekCapitalEta => 'Ⲏ',
            KnownCharacter.GreekCapitalTheta => 'Ⲑ',
            KnownCharacter.GreekCapitalIota => 'Ⲓ',
            KnownCharacter.GreekCapitalKappa => 'Ⲕ',
            KnownCharacter.GreekCapitalLambda => 'Ⲗ',
            KnownCharacter.GreekCapitalMu => 'Ⲙ',
            KnownCharacter.GreekCapitalNu => 'Ⲛ',
            KnownCharacter.GreekCapitalXi => 'Ⲝ',
            KnownCharacter.GreekCapitalOmicron => 'Ⲟ',
            KnownCharacter.GreekCapitalPi => 'Ⲡ',
            KnownCharacter.GreekCapitalRho => 'Ⲣ',
            KnownCharacter.GreekCapitalSigma => 'Ⲥ',
            KnownCharacter.GreekCapitalTau => 'Ⲧ',
            KnownCharacter.GreekCapitalUpsilon => 'Ⲩ',
            KnownCharacter.GreekCapitalPhi => 'Ⲫ',
            KnownCharacter.GreekCapitalChi => 'Ⲭ',
            KnownCharacter.GreekCapitalPsi => 'Ⲯ',
            KnownCharacter.GreekCapitalOmega => 'Ⲱ',
            KnownCharacter.GreekSmallAlpha => 'ⲁ',
            KnownCharacter.GreekSmallBeta => 'ⲃ',
            KnownCharacter.GreekSmallGamma => 'ⲅ',
            KnownCharacter.GreekSmallDelta => 'ⲇ',
            KnownCharacter.GreekSmallEpsilon => 'ⲉ',
            KnownCharacter.GreekSmallZeta => 'ⲍ',
            KnownCharacter.GreekSmallEta => 'ⲏ',
            KnownCharacter.GreekSmallTheta => 'ⲑ',
            KnownCharacter.GreekSmallIota => 'ⲓ',
            KnownCharacter.GreekSmallKappa => 'ⲕ',
            KnownCharacter.GreekSmallLambda => 'ⲗ',
            KnownCharacter.GreekSmallMu => 'ⲙ',
            KnownCharacter.GreekSmallNu => 'ⲛ',
            KnownCharacter.GreekSmallXi => 'ⲝ',
            KnownCharacter.GreekSmallOmicron => 'ⲟ',
            KnownCharacter.GreekSmallPi => 'ⲡ',
            KnownCharacter.GreekSmallRho => 'ⲣ',
            KnownCharacter.GreekSmallFinalSigma or
            KnownCharacter.GreekSmallSigma => 'ⲥ',
            KnownCharacter.GreekSmallTau => 'ⲧ',
            KnownCharacter.GreekSmallUpsilon => 'ⲩ',
            KnownCharacter.GreekSmallPhi => 'ⲫ',
            KnownCharacter.GreekSmallChi => 'ⲭ',
            KnownCharacter.GreekSmallPsi => 'ⲯ',
            KnownCharacter.GreekSmallOmega => 'ⲱ',
            _ => ConvertToUnicode(c)
        };
    }

    private static char ConvertToAthanasius(KnownCharacter c)
    {
        return c switch
        {
            KnownCharacter.ExclamationMark => '¡',
            KnownCharacter.Ampersand => '¶',
            KnownCharacter.LeftParenthesis => '(',
            KnownCharacter.RightParenthesis => ')',
            KnownCharacter.Asterisk => '*',
            KnownCharacter.PlusSign => '§',
            KnownCharacter.Comma => '%',
            KnownCharacter.HyphenMinus => '-',
            KnownCharacter.FullStop => '.',
            KnownCharacter.Colon => '>',
            KnownCharacter.Semicolon => '^',
            KnownCharacter.EqualsSign => '•',
            KnownCharacter.QuestionMark => '&',
            KnownCharacter.CombiningGraveAccent => '`',
            KnownCharacter.CombiningOverline => '/',
            KnownCharacter.GreekCapitalAlpha => 'A',
            KnownCharacter.GreekCapitalBeta => 'B',
            KnownCharacter.GreekCapitalGamma => 'G',
            KnownCharacter.GreekCapitalDelta => 'D',
            KnownCharacter.GreekCapitalEpsilon => 'E',
            KnownCharacter.GreekCapitalZeta => 'Z',
            KnownCharacter.GreekCapitalEta => 'H',
            KnownCharacter.GreekCapitalTheta => 'Q',
            KnownCharacter.GreekCapitalIota => 'I',
            KnownCharacter.GreekCapitalKappa => 'K',
            KnownCharacter.GreekCapitalLambda => 'L',
            KnownCharacter.GreekCapitalMu => 'M',
            KnownCharacter.GreekCapitalNu => 'N',
            KnownCharacter.GreekCapitalXi => '{',
            KnownCharacter.GreekCapitalOmicron => 'O',
            KnownCharacter.GreekCapitalPi => 'P',
            KnownCharacter.GreekCapitalRho => 'R',
            KnownCharacter.GreekCapitalSigma => 'C',
            KnownCharacter.GreekCapitalTau => 'T',
            KnownCharacter.GreekCapitalUpsilon => 'U',
            KnownCharacter.GreekCapitalPhi => 'V',
            KnownCharacter.GreekCapitalChi => 'X',
            KnownCharacter.GreekCapitalPsi => 'Y',
            KnownCharacter.GreekCapitalOmega => 'W',
            KnownCharacter.GreekSmallAlpha => 'a',
            KnownCharacter.GreekSmallBeta => 'b',
            KnownCharacter.GreekSmallGamma => 'g',
            KnownCharacter.GreekSmallDelta => 'd',
            KnownCharacter.GreekSmallEpsilon => 'e',
            KnownCharacter.GreekSmallZeta => 'z',
            KnownCharacter.GreekSmallEta => 'h',
            KnownCharacter.GreekSmallTheta => 'q',
            KnownCharacter.GreekSmallIota => 'i',
            KnownCharacter.GreekSmallKappa => 'k',
            KnownCharacter.GreekSmallLambda => 'l',
            KnownCharacter.GreekSmallMu => 'm',
            KnownCharacter.GreekSmallNu => 'n',
            KnownCharacter.GreekSmallXi => '[',
            KnownCharacter.GreekSmallOmicron => 'o',
            KnownCharacter.GreekSmallPi => 'p',
            KnownCharacter.GreekSmallRho => 'r',
            KnownCharacter.GreekSmallFinalSigma or
                KnownCharacter.GreekSmallSigma => 'c',
            KnownCharacter.GreekSmallTau => 't',
            KnownCharacter.GreekSmallUpsilon => 'u',
            KnownCharacter.GreekSmallPhi => 'v',
            KnownCharacter.GreekSmallChi => 'x',
            KnownCharacter.GreekSmallPsi => 'y',
            KnownCharacter.GreekSmallOmega => 'w',
            KnownCharacter.CopticCapitalAlpha => 'A',
            KnownCharacter.CopticCapitalVida => 'B',
            KnownCharacter.CopticCapitalGamma => 'G',
            KnownCharacter.CopticCapitalDalda => 'D',
            KnownCharacter.CopticCapitalEie => 'E',
            KnownCharacter.CopticCapitalSou => '<',
            KnownCharacter.CopticCapitalZata => 'Z',
            KnownCharacter.CopticCapitalHate => 'H',
            KnownCharacter.CopticCapitalThethe => 'Q',
            KnownCharacter.CopticCapitalIauda => 'I',
            KnownCharacter.CopticCapitalKapa => 'K',
            KnownCharacter.CopticCapitalLaula => 'L',
            KnownCharacter.CopticCapitalMi => 'M',
            KnownCharacter.CopticCapitalNi => 'N',
            KnownCharacter.CopticCapitalKsi => '{',
            KnownCharacter.CopticCapitalO => 'O',
            KnownCharacter.CopticCapitalPi => 'P',
            KnownCharacter.CopticCapitalRo => 'R',
            KnownCharacter.CopticCapitalSima => 'C',
            KnownCharacter.CopticCapitalTau => 'T',
            KnownCharacter.CopticCapitalUa => 'U',
            KnownCharacter.CopticCapitalFi => 'V',
            KnownCharacter.CopticCapitalKhi => 'X',
            KnownCharacter.CopticCapitalPsi => 'Y',
            KnownCharacter.CopticCapitalOou => 'W',
            KnownCharacter.CopticCapitalShei => '}',
            KnownCharacter.CopticCapitalFei => 'F',
            KnownCharacter.CopticCapitalAkhmimicKhei or
                KnownCharacter.CopticCapitalKhei => '\"',
            KnownCharacter.CopticCapitalHori => '|',
            KnownCharacter.CopticCapitalGangia => 'J',
            KnownCharacter.CopticCapitalShima => 'S',
            KnownCharacter.CopticCapitalDei => ':',
            KnownCharacter.CopticSmallAlpha => 'a',
            KnownCharacter.CopticSmallVida => 'b',
            KnownCharacter.CopticSmallGamma => 'g',
            KnownCharacter.CopticSmallDalda => 'd',
            KnownCharacter.CopticSmallEie => 'e',
            KnownCharacter.CopticSmallSou => '<',
            KnownCharacter.CopticSmallZata => 'z',
            KnownCharacter.CopticSmallHate => 'h',
            KnownCharacter.CopticSmallThethe => 'q',
            KnownCharacter.CopticSmallIauda => 'i',
            KnownCharacter.CopticSmallKapa => 'k',
            KnownCharacter.CopticSmallLaula => 'l',
            KnownCharacter.CopticSmallMi => 'm',
            KnownCharacter.CopticSmallNi => 'n',
            KnownCharacter.CopticSmallKsi => '[',
            KnownCharacter.CopticSmallO => 'o',
            KnownCharacter.CopticSmallPi => 'p',
            KnownCharacter.CopticSmallRo => 'r',
            KnownCharacter.CopticSmallSima => 'c',
            KnownCharacter.CopticSmallTau => 't',
            KnownCharacter.CopticSmallUa => 'u',
            KnownCharacter.CopticSmallFi => 'v',
            KnownCharacter.CopticSmallKhi => 'x',
            KnownCharacter.CopticSmallPsi => 'y',
            KnownCharacter.CopticSmallOou => 'w',
            KnownCharacter.CopticSmallShei => ']',
            KnownCharacter.CopticSmallFei => 'f',
            KnownCharacter.CopticSmallAkhmimicKhei or
                KnownCharacter.CopticSmallKhei => '\'',
            KnownCharacter.CopticSmallHori => '\\',
            KnownCharacter.CopticSmallGangia => 'j',
            KnownCharacter.CopticSmallShima => 's',
            KnownCharacter.CopticSmallDei => ';',
            KnownCharacter.CopticMiRo => '=',
            KnownCharacter.CopticShimaSima => '_',
            KnownCharacter.CopticGammaRoSima => '+',
            _ => '\0'
        };
    }
}