using System.Collections.Generic;
using System.Xml.Serialization;

namespace CoptLib.Models
{
    /// <summary>
    /// An interface for anything that can be defined in a <see cref="Doc"/>.
    /// </summary>
    public interface IDefinition
    {
        /// <summary>
        /// A key that can be used to identify this definition.
        /// </summary>
        string Key { get; set; }

        /// <summary>
        /// The document this definition belongs to.
        /// </summary>
        Doc DocContext { get; set; }

        /// <summary>
        /// The parent definition, if any.
        /// </summary>
        IDefinition Parent { get; set; }

        /// <summary>
        /// Whether the definition was defined explicitly as opposed to
        /// generated by a script or the result of a text command.
        /// </summary>
        bool IsExplicitlyDefined { get; set; }

        /// <summary>
        /// Gets all definitions that reference this definition.
        /// </summary>
        IList<IDefinition> References { get; }
    }

    /// <summary>
    /// A base class for any object that can be referenced by other objects.
    /// </summary>
    public abstract class Definition : IDefinition
    {
        [XmlAttribute]
        public string Key { get; set; }

        [XmlIgnore]
        public Doc DocContext { get; set; }

        [XmlIgnore]
        public IDefinition Parent { get; set; }

        [XmlIgnore]
        public bool IsExplicitlyDefined { get; set; }

        [XmlIgnore]
        public IList<IDefinition> References { get; } = new List<IDefinition>();
    }

    public class Variable : Definition
    {
        [XmlAttribute]
        public bool Configurable { get; set; }

        [XmlAttribute]
        public string Label { get; set; }

        [XmlAttribute]
        public object DefaultValue { get; set; }
    }
}
